name: m2-actions-test
on: [push]


jobs:
   build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: 'show mode magento2'
        run: ls
        working-directory: magento/bin
      - name: 'show mode magento2'
        run: magento deploy:mode:show
        working-directory: magento/bin
      - run: rm -rf magento/generated/metadata/* magento/generated/code/* 
      - run: bin/magento deploy:mode:set developer
        working-directory: ./magento
      - name: 'sample data'
        run: bin/magento sampledata:deploy
        working-directory: ./magento
